---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php packages for RedHat
    package:
      name: 
#        - httpd.x86_64
        - httpd.x86_64
        - php
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Install apache2 and php packages for Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
