---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (RedHat)
    tags:  always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.4.0-alpha20221207/terraform_1.4.0-alpha20221207_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks: 

  - name: Install apache2 and php packages for RedHat
    tags: apache,apache2,httpd,RedHat
    package:
      name:
        - httpd.x86_64
        - php
    when: ansible_distribution == "RedHat"

  - name: Copy default html for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      owner: root
      mode: 0644

  - name: Start httpd (RedHat)
    tags: apache,RedHat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: Change email address for admin
    tags: apache,RedHat,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.com
    when: ansible_distribution == "RedHat"
    register: httpd

  - name: Restart httpd (RedHat)
    tags: apache,RedHat,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

- hosts: db_servers
  become: true
  tasks:

  - name: Install Mariadb package (RedHat)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install Mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package:
      name: samba
      state: latest
